id = "CertifiedPyro.InventoryTweaks"
name = "Inventory_Tweaks"
description = "Adds inventory sorting, for a cleaner inventory!"
version = "1.0.0"
homepage = "https://github.com/CertifiedPyro/InventoryTweaks"
author = "CertifiedPyro"

icon = "./thunderstore/icon.png"
readme = "./thunderstore/README.md"
changelog = "./thunderstore/CHANGELOG.md"

# both are optional here, pick what you want
[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.12"
